### ISSUE TITLE
robot_name nearly impossible test

### ISSUE THREAD

**Issue by dalexj** [exercism/xjavascript#105]
the robot names are 2 letters and 3 numbers, for a possibility of about `26 * 26 * 10 * 10 * 10` (676000) different names.

pulling the same name randomly 2 times in a row would then be a 1 in 676000 chance, almost impossible, but the test wants 10001 unique names after 10001 pulls. now there's much more chance for overlap.

after running the suite several times, I've almost always gotten around 9900-9940 unique names pulled from the 10001 the test expects.

I get the need to check if these are different names, but because of the randomness it is impossible to test. maybe the best approach is to check if there is _enough_ randomness, and look for more than 9800-9900 unique names of the 10001?

**Comment by kytrinyx** [comment]
I'm not particularly attached to the robot name exercise as it stands, and would be happy to discuss improvements or variants. I'd be interested in hearing what others think. /cc @exercism/track-maintainers

**Comment by etrepum** [comment]
It could be changed to generate serial numbers sequentially, maybe even add a function to render the Nth serial number for easy testing

**Comment by kytrinyx** [comment]
I like that--much simpler without actually changing the shape of the problem.

**Comment by kotp** [comment]
Without a 'seed' function in Javascript how do you check?  Also, with testing things random, just because it comes up with the same name 1000 times in no way invalidates a random result.  So then the question becomes "Are you testing something that is hard as in "Computer Science" or testing something a little bit simpler as outlined by the requirements?"

Perhaps the test itself is misleading... Or there should be a requirement to check and discard if the prior name is the same as the new name.

The problem really is in solving the "random - enough" question, given the characteristics of what it means to be 'random'.  Unlikely, but not impossible for repeating any number of times.

Perhaps the test itself is attempting to test he wrong thing here.

**Comment by hankturowski** [comment]
I just looked and not all language tracks don't have the 10000 name check in their test suites. I spot checked Ruby, Swift and Python and they're just checking to see that two sequential names do not conflict. My advice is to just remove the test from the JavaScript suite.

I would love to see us put some effort into creating a canonical core set of unit tests for each exercise. We already have the ability to add a .json file which describes tests in x-common alongside the .md and .yml files. Would you guys be up for starting to fill out the missing ones (there are only a couple there now) then updating our tracks to conform? We could divvy them up to avoid initial duplication, then cross check the rest against our own languages and update as needed.

There will of course be implementation variation based on the individual language capabilities and not all tests will be appropriate for your language, but having a core list would make things so much nicer. It will keep the exercises uniform across language tracks, make it much easier to port exercises to a new language, and make sure that the tests we have are of good quality.

Writing good unit tests is hard, and it would be nice if we could be sure that the tests we use here are of good quality.

**Comment by kotp** [comment]
It seems to me that more than a uniform test suite, there should be a checklist of what each exercise is trying to exercise.  A Lesson Objective, perhaps.  That will direct the points that would be tested.

In this case, apparently the slip is that at some point someone thought the randomness was the goal of the exercise.  I thought the goal was working with numbers and strings in a random way, sure but the important part was really working with these two things together to form some kind of pattern in a requirement.  The randomness wasn't really a priority, but the restriction that the name should be guarded against being the same in a reset of that robot.

**Comment by hankturowski** [comment]
That objective information can either go into the comment block at the top of the .json file, or into the .md. Having said that, I believe that well written test will serve to document the intent of the exercise.

**Comment by kotp** [comment]
Of course it can, and it does.  As demonstrated even here.  I think the problem is that the intent shifts without a control or limit reminding of the uniform goal.

I think that may be what happened here.  Someone thought that it was a 'randomness' that was part of the objective.

I think you are saying the same thing though, but I may be wrong.

Is the .json file too far away from the test?  Do you think it should be incorporated in the test file itself to keep it apparent and up front?

**Comment by hankturowski** [comment]
We're on exactly the same page. I agree that the issue is that there wasn't clear indication about the purpose of the exercise.

I'm not sure about incorporating the .json directly into the test, to be honest. I was just thinking about clearing up some of the ambiguity, not the next steps. How do you see that working? Like having a tool to auto-generate the tests from the JSON? Or just having the information there in the test file so that it can be easily accessed?

**Comment by wobh** [comment]
The README used to have a line about making robot names both random and unique as a challenge for "bonus points".  I suppose that text was removed since we don't actually have "points" much less bonus ones. We could restore that notion in the README as a more advanced challenge, and comment out the test as optional.

We don't have such a test in the xlisp version but I would totally add it under those conditions.

**Comment by kytrinyx** [comment]
> I would love to see us put some effort into creating a canonical core set of unit tests for each exercise. - @hankturowski 

I would really love to see this happen, even to the point of creating generators, which we've started doing in the Go and Ruby tracks.

I started a high-level "todo" for this a while back: https://github.com/exercism/todo/issues/13

If there is any interest in pursuing this, I would love to have some help thinking through how we might make this a community-wide effort. One thing that I've noticed is that a lot of people who are quite new to programming really would love to get into open source, but are intimidated for a number of reasons, many of which are absolutely legitimate. I would love for Exercism to become a friendly way to get your feet wet in open source. This is a project that would not require a whole lot of context about the entire code-base, and so it could make it a good project to get newer programmers involved.

> It seems to me that more than a uniform test suite, there should be a checklist of what each exercise is trying to exercise. A Lesson Objective, perhaps. That will direct the points that would be tested. - @kotp 

I think that this is different and equally valuable. I think that this ties into the ideas that Peter mentioned in https://github.com/exercism/x-common/issues/63 -- in addition to classifying each exercise, it would be really useful to have higher level objectives... where possible. Where it's not possible, then perhaps that's a good indication that the exercise could use some more thought, perhaps.

> I suppose that text was removed since we don't actually have "points" much less bonus ones. - @wobh 

Yeah, exactly this. I don't want this to feel like a competition in any way.

> We could restore that notion in the README as a more advanced challenge, and comment out the test as optional. - @wobh 

Yeah, I think it would be great to start looking at additional challenges and describing them in the README.

**Comment by verdammelt** [comment]
I like the idea of the README hinting at further challenges. With this exercise in the Common Lisp track i know that @wobh and I have both prompted people to consider the uniqueness of the names and that created interesting code and discussions.
