### ISSUE TITLE
Update nodejs version?

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/xjavascript#165]
@kytrinyx @rchavarria is there a reason we're running node 0.10 on Travis?  It's on 5.6 now.

**Comment by kytrinyx** [comment]
Hah. No, that would be because I don't know the first thing about javascript.

**Comment by matthewmorgan** [comment]
You say that like it's a point of pride 😉

**Comment by kytrinyx** [comment]
Nooooo, imagine me sighing and throwing my hands in the air. I am going to have to learn javascript properly, maybe even soon. Exercism is going to require a technical overhaul before too long. We're starting to see the effects of all the duct tape on performance.

**Comment by matthewmorgan** [comment]
Anecdotally my local JS group have been using exercism.io once a month, and
it does tend to bog down. Don't know if that is what you're seeing.

**Comment by kytrinyx** [comment]
I'm seeing a number of things. One of the features ('5 a day') was taking the database down when certain users logged on (not even sure which users). I temporarily removed the feature, and will look at reimplementing it. The side is really slow, some pages more than others, and it's a combination of a number of things: unoptimized database stuff, too many calls to the database, very little caching for critical bits of data, probably not gzipping javascript and CSS, lots of unnecessary bloat pretty much everywhere, very inefficient code (due to experiment after experiment in order to figure out what exercism is all about in the first place).
