### ISSUE TITLE
leap year expects a JS class instead of simple function

### ISSUE THREAD

**Issue by justgage** [exercism/xjavascript#282]
I find it odd that the [leap year](http://exercism.io/exercises/javascript/leap) exercise expects either a ES6 class or an old style sudo-classical class. I don't think that it's generally a good idea to encourage beginners towards classes in JavaScript especially in places where a simple function would do just fine like so:

```js
// have to pass in the year every time
module.exports = (year) => { 
  !!(!(year % 4) && year % 100 || !(year % 400)); 
}
```
Instead of:

```js
module.exports = class Year {
  constructor(year) {
    this.year = year;
  },
  isLeap() {
    return !!(!(this.year % 4) && this.year % 100 || !(this.year % 400));
  }
}
```

I'm guessing this is an artifact from the fact that it was ported from a Java exercise [http://www.javaranch.com/leap.jsp](http://www.javaranch.com/leap.jsp)

**Comment by matthewmorgan** [comment]
@justgage thanks for your feedback.

A decision was made a while back to make the required API between the tests and the submissions consistent for the first several (12 I think?) exercises.  Previously, some tests expected a simple function, some expected something that looked more like a class.  We felt the inconsistency was confusing for beginners and a source of possible frustration in getting started.  Since some of the exercises do require more complex interfaces, we decided to err on the side of consistency even though the "Leap" exercise can be solved with a simple one line function.

Having said that, there are many interesting ways to solve that problem, and many of them do not involve ES6 style classes.  I won't reproduce them here, but if you are curious, please have a look at the following sets of solutions:

http://exercism.io/submissions/98a21726f716445381cf8ce18f95eba6

http://exercism.io/submissions/9b476c42641c4977bb4156b00d2b770b (and previous iterations by the same author)

Finally, my own:
http://exercism.io/submissions/be40886cfaaf4e03bd1e8a7805f59746

I think "Leap" is a great example of an exercise that is trivial at its core, but allows you to explore and discuss a variety of approaches that would transfer to a more complex problem down the road.

**Comment by justgage** [comment]
Thanks for getting back to me. 

I personally feel that the confusion is a _good_ thing for beginners. I think that it's important to realize early that what is considered best practice in one language is not considered best practice in another. I don't see any value in teaching how to program like a Java programmer using the syntax of 20 different languages, especially in a language like JavaScript that's already too tempting to bring old habits to. 

It looks like the ES track actually accepts a simple function (the way I wish it was in the JS track)

```js
  it('is not very common', () => {
    expect(isLeapYear(2015)).toBeFalsy();
  });
```

That being said, perhaps a compromise would be to keep the exercise the same but then quickly introduce a function-only one (like the ES one) to help show the contrast of how much less code it is. My only concern would be if that would be confusing for people though (didn't I just solve this?)

_ps: those where some cool solutions_

**Comment by justgage** [comment]
To maybe make my argument more directed, I think the worst part of this is that it requires people to use something compatible with the `new` keyword. The main problem is this adds a lot of confusion. I think this quote from [David Crockford](http://javascript.crockford.com/prototypal.html) helps illustrate that point:

> "My journey was circuitous because JavaScript itself is conflicted about its prototypal nature. In a prototypal system, objects inherit from objects. JavaScript, however, lacks an operator that performs that operation. Instead it has a new operator....
>
> This indirection was intended to make the language seem more familiar to classically trained programmers, but failed to do that, as we can see from the very low opinion Java programmers have of JavaScript. JavaScript's constructor pattern did not appeal to the classical crowd. It also obscured JavaScript's true prototypal nature. **As a result, there are very few programmers who know how to use the language effectively.**"

If nothing else I feel that we should remove the "new" keyword so that you can use a normal object literal.

**Comment by matthewmorgan** [comment]
Thanks for your carefully considered thoughts.  I agree this could potentially be a bit confusing, and it's not good to confuse newbies.

We made a decision to embrace the 'new' features of the language like classes in the first twelve exercises, in part because these features aren't new anymore, but mostly to present a consistent interface to the tests.

So, all the early exercise tests encourage the creation of class.  As a fan of Crockford, I would point out that you could also use one of my favorite styles, the 'revealing' pattern, AKA Crockford Classless.

For example, `leap` can be solved like so:
```
module.exports = function (year) {
  function isLeap() {
    return year % 400 === 0 || year % 4 === 0 && year % 100 !== 0
  }

  return { isLeap }
};
```
I think this is a lovely style and allows the programmer to construct a well defined public API.

@rchavarria do you have any input on this discussion?

**Comment by justgage** [comment]
@matthewmorgan Wow, I learned something today! I tried the following code:

```
module.exports = (year) => {
  return {
    isLeap() {
      return !!(!(year % 4) &&
                year % 100 ||
                !(year % 400));
    }
  }
}
```

Which creates the following error:
```
λ ~/exercism/javascript/leap/ jasmine-node leap.spec.js
FFFFFFFF

Failures:

  1) Leap year is not very common
   Message:
     TypeError: Year is not a constructor
   Stacktrace:
     TypeError: Year is not a constructor
    at .<anonymous> (/home/justgage/exercism/javascript/leap/leap.spec.js:6:16)
...
```

However changing it to `function` fixes this. Turns out I learned something about some of the differences of arrow functions!

However I do feel that the __very presence__ of the `new` operator leads people to use solve the problem with pseudo-classical inheritance (possibly due to [googling it](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8&client=ubuntu#q=javascript%20new))

I took a short sample of posts this is about what I get as far as how people solve it:
```
the 'revealing' pattern: 1
Constructor Functions:   1111111111111111111111111111
ES6 Class:               1111
```

It seems like as x goes to infinity the constructor function becomes the only way to solve it :P. 

Either way I feel satisfied that I can at least guide people to a better way now, although I do wish the exercise was better about leading people to better patterns.

**Comment by rchavarria** [comment]
@matthewmorgan I have nothing to add here. You explained it perfectly. A decision was made. It satisfies some points of view and it lets other not as satisfied.

I think it was a good decision to make the first exercises to require the same technique. Are classes the right way of solving problems? Not always. There are other ways? Absolutely, specially in JavaScript.

But I think that *classy* approach could be the most known one. Most common languages are C/C++ based. Does it mean there aren't other languages? Absolutely not! But I think we took the most known way.

I agree on having the same way of solving things in the first exercises is a good way of helping people to learn the language. Of course, it shouldn't be seen as something to teach THE way of solving problems, but I think it helps people to start doing it. If then, they get some experience and they realize there is a better way. Congratulations! They're learning! That's the goal!

**Comment by justgage** [comment]
@rchavarria I do find it odd that this became _thee_ way of doing this (wrapping a single function in a class that saves it's state for no reason). Especially because the large majority of languages (Python, Ruby, C++, C, Go, JavaScript, Lisp, Haskell, Clojure, Lua, Perl...) can have standalone functions. The only ones that I'm aware of that can't is Java and C# (maybe I'm not sure). In a twist of fate the Java doesn't even have this exercise at all (although C# does). 

**Anyway** I think I've dragged this on too long, and it's not of much consequence so I'll close this now.
