### ISSUE TITLE
installing json and jasmine-node package

### ISSUE THREAD

**Issue by jsoranno** [exercism/xjavascript#284]
I've needed to Google a lot to figure out why I couldn't run the test for the Hello World tutorial. I'm running on OSX 10.11.4 and I needed to do the following:
Installed Homebrew
$ brew update && brew install exercism
$ exercism --version
$ exercism configure --key=_(mine)_
$ exercism fetch javascript hello-world
$ jasmine-node .     // didn't work
$ sudo npm install jasmine-node -g
$ jasmine-node . // tried again and it spit back
(node) sys is deprecated. Use util instead. // I have no idea what that means, so I kept Googling
$ npm init // Then I created some json package that I don't completely understand... after working through the setup wizard
$ npm install jasmine-node --save
$ cd exercism
$ jasmine-node . // FINALLY!!! 

Is there a way to add in the $cd exercism instructions after all of the install instructions, but before doing the first test? Should I create a pull request? Or maybe this exists somewhere and I didn't come across it...

**Comment by rchavarria** [comment]
I understand, very frustrating.

The recommended way of running tests is explicitly name the spec file (file with the tests):

    $ jasmine-node hello-world.spec.js

I don't know if just `jasmine-node .` does the work. Apparently, for your `// FINALLY!!` comment it works.

I'm not sure, but following the steps you describe, I think you're missing a very important one. Navigate to the folder where the exercise is fetched. When you run

    $ exercism fetch javascript hello-world

It fetches some files and put them under

    <EXERCISM_HOME_FOLDER>/javascript/hello-world

where `<EXERCISM_HOME_FOLDER>` is `~/exercism` by default (see [command-line interface documentation](http://exercism.io/cli) to learn more about the `exercism` tool, how to configure it, ...).

So, after fetching the exercise, you should navigate to `~/exercism/javascript/hello-world`. Then, if you installed `jasmine-node` globally (with the `-g` option of `npm`) you should be able to run tests with `jasmine-node hello-world.spec.js`.

@kytrinyx I'm not able to find a reference in the documentation about navigating to the folder where `exercism` tool put fetched files. Do you think it would be necessary to state it somewhere? I'd love to help.

**Comment by kytrinyx** [comment]
It depends on the language you're working in. In Java there's a whole directory tree that gets fetched. Maybe we can suggest that people navigate to the folder of the exercise, so `<EXERCISM_HOME_DIR>/<TRACK_ID>/<EXERCISE>` and work from there. I *think* that should work for all the languages.

**Comment by joelwallis** [comment]
Specifically speaking about the JavaScript track I had the same issue yesterday (Apr 10, 2017). It seems that it's using a different version of Jasmine than what's available in [Jasmine website](https://jasmine.github.io/).

The Jasmine's Getting Started says that, in order to install Jasmine you just need to `npm install jasmine`. We could instead advise people to install Jasmine globally, since dealing with packages are not so straightforward.

So, `npm i -g jasmine` could be in the `README.md` file, and a proper explanation that one must run `jasmine ./<exercise-name>.spec.js` in order to run the automated tests.

Please let me know what are your thoughts so I can provide a PR that adds these instructions to the affected exercises.

**Comment by joelwallis** [comment]
Btw, @jsoranno I could solve the issue by:

```sh
# installing Jasmine
$ npm install -g jasmine

# running the `jasmine` command with the test suite as parameter
$ jasmine ./hello-world.spec.js
```

**Comment by kytrinyx** [comment]
> We could instead advise people to install Jasmine globally, since dealing with packages are not so straightforward.

I think that it's worth suggesting it, unless the JavaScript world thinks it's generally a terrible idea to do that. I don't know, since I don't write JavaScript on a regular basis.

@rchavarria thoughts?

**Comment by rchavarria** [comment]
In the current documentation, the recommended package to install is `jasmine-node`. And it's suggested to install it globally.

Of course, it's not recommended to install all packages globally, but in this case I think it's ok. The package is installed as a command line tool, not a dependency for a project (like a needed library or so). And installing it globally prevents users to install it on every exercise and making it available to the path to be able to execute the command.

In a recent discussion (#315, that caused to open a new issue, #341), @joelwallis recommended to use `jasmine` instead of `jasmine-node`. And I like the idea. `jasmine` should work as well as `jasmine-node`. It should be installed globally too (reasons above: command line tool, no library,...).

The discussion about `jasmine` or `jasmine-node` could continue on #341.

**Comment by kytrinyx** [comment]
> The package is installed as a command line tool, not a dependency for a project

I hadn't thought of this distinction, but now that you mention it, it makes sense.

Conclusion (I think) is that we should update the documentation to clearly suggest installing the library globally. Counter-suggestions?

**Comment by matthewmorgan** [comment]
I'm fine with this!

**Comment by joelwallis** [comment]
Awesome!

Can I work on it? 😄  😄  😄

**Comment by kytrinyx** [comment]
> Can I work on it?

🎉 🎉 🎉 💯 YES 💯 🎉 🎉 🎉

**Comment by joelwallis** [comment]
@kytrinyx this work is being done on #341, and since it's a support issue I think it's OK to be closed now :)

**Comment by rchavarria** [comment]
I'll close this issue, since it seems #341 is completed. Let me know if this issue should be reopened.
