### ISSUE TITLE
Suggest migrating to mocha or chai instead of jamine-node

### ISSUE THREAD

**Issue by mcshaman** [exercism/xjavascript#315]
I have been trying to read up on an issue that jasmine-node has been throwing at me when testing my exercises however I it seems that jasmine-node appears to be an abandoned project so getting support seems difficult.

Would it be better to migrate to some other testing library like mocha or chai so that it is more likely to support testing of new JS development ideologies and also have better support?

**Comment by rchavarria** [comment]
Hmmm. Not sure about `jasmine-node`. It's just a wrapper to run [Jasmine](https://jasmine.github.io/) test suites with Node. So, the real work is done by Jasmine, and I think its development is active and well maintained.

I personally think that Mocha+Chai would be a more flexible solution. But, to be pragmatic, Jasmine is more than enough for the tests needed to describe exercises for exercism.io. And changing the test framework would require modifications in all exercises. Changing the test framework may cause current solutions to stop working, and it may be confusing for exercism.io users.

Let's see what other @exercism/javascript maintainers and other contributors have to say about this idea.

BTW: would you need help with that issue `jasmine-node` is throwing at you? Feel free to open a new issue to ask for help,

**Comment by rchavarria** [comment]
@exercism/javascript, any ideas/preferences on this?

**Comment by joelwallis** [comment]
[Jasmine is not abandoned or unmaintained](https://github.com/jasmine/jasmine/commits/master). The big issue here is that `jasmine-node` is not the current command used by Jasmine.

If you install Jasmine by following [the official instructions](https://jasmine.github.io/pages/getting_started.html) (using Node.js: `npm i -g jasmine`) you'll have a `jasmine` command available, but docs says that it's `jasmine-node`. If we change the README.md to use `jasmine` instead of `jasmine-node` we would be fine.

**Comment by rchavarria** [comment]
Ok, great! I knew Jasmine was maintained, but I didn't know `jasmine` (as npm package) could run tests too.

I agree, it would be a nice idea to update this track's documentation to reference `jasmine` instead of `jasmine-node`.

I'll create a new issue and close this one.
