### ISSUE TITLE
Is unicode introduced too early in the list?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xjavascript#321]
Bob is currently 5th exercise, and Word Count is currently the 7th exercise.

Both introduce unicode. If JavaScript is your first programming language, dealing with encoding is a pretty big hurdle. My guess is that a lot of people who tackle the JavaScript track on Exercism are new to programming.

For Bob it can be handled by the standard library function `toLocaleUpperCase()`, but if you're a beginner to programming, I'm not sure that you'd know to google for "string functions".

For Word Count it looks like we're tackling some pretty juicy stuff that isn't trivially solved with looking up string functions.

**Comment by rchavarria** [comment]
Yep, I agree encoding is not the friendliest concept in programming. I don't remember exactly, but I think I solved one of them or both with regular expressions, and that's not very friendly neither for beginners.

I also think JavaScript is one of the first choices for beginners, because it's easy to start programming with it.

Are you suggesting we should move them further than the 10th position?

**Comment by kytrinyx** [comment]
> Are you suggesting we should move them further than the 10th position?

Yeah. I think Bob is probably fine (I'd be curious to hear from some people who are doing the JavaScript track what they think, actually), but I would suggest moving Word Count out to position 20 at least.

**Comment by kytrinyx** [comment]
I would recommend putting Pangram earlier, since it doesn't deal in unicode at all.

**Comment by behrtam** [comment]
The unicode aspect was removed from many exercises in the `x-common` test data: https://github.com/exercism/x-common/issues/441

**Comment by rchavarria** [comment]
Thanks for the reference @behrtam!

**Comment by rchavarria** [comment]
As exercises were reordered, I'm going to close this issue.
