### ISSUE TITLE
Bob test suite only performing one test

### ISSUE THREAD

**Issue by DouglasBrunner** [exercism/xjavascript#33]
The test suite is only performing one test and then passing me. Here is the output from the test suite.

> I haven't modified the test suite in any way.

```
D:\Doug\exercism\javascript\bob>jasmine-node bob_test.spec.js
.

Finished in 0.012 seconds
1 test, 1 assertion, 0 failures, 0 skipped
```

Here is my Bob.js 

> I purposely returned the wrong strings to make tests fail.

```
var Bob = function() {
    'use strict';

    this.hey = function(message) {

        function isYelling (message) {
            var re = /[^\w]/gi;
            var ALPHAS = message.replace(re, '');   
            return ALPHAS.toUpperCase() == message && ALPHAS != ""
        }

        function isSilence(message) {
            var re = /\s+/g;
            return message.replace(re, '') === ""
        }

        function isQuestion (message) {
            return message.charAt(message.length - 1) === "?";
        }

        if (isYelling(message)) {
            return "Woah, chill out!*";
        } else if (isSilence(message)) {
            return "Fine. Be that way!**";
        } else if (isQuestion(message)) {
            return "Sure.**";
        } else {
            return "Whatever.";
        } 
    }
};
module.exports = Bob;
```

I'm on windows 7 and have installed Node.js according to the instructions provided.

If you need any other info let me know.

**Comment by ZacharyRSmith** [comment]
Hi Katrina, I'm wondering if you'd like me to work on implementing any of the above-mentioned ideas?

**Comment by kytrinyx** [comment]
That would be wonderful! If you have any specific questions, don't hesitate to holler. Also, if you have any co-conspirators that can help whip the javascript into shape, that would be wonderful :) As I've discovered while watching the folks who are managing all the various lisp tracks, this is a lot of fun with friends!

**Comment by joelwallis** [comment]
Hello, @kytrinyx and @ZacharyRSmith.

I know that this issue is quite old for now, but I would really like to know if there have been some progress in this matter. I would like to contribute, but I'm a newbie in the Exercism community.

How does this kind of decisions (organization of infos, instructions, etc.) are made? Is this the correct place to discuss it or does Exercism maintains a proper place for decisions that could affect more than one language track?

**Comment by joelwallis** [comment]
Well, this issue started as a support request and then evolved into a discussion about multiple topics. Since the original objective was achieved (the user is now able to run the remaining tests) I think it's OK to close this one.

If there are still pending tasks (like a missing stub file in Bob exercise) a new issue specific to this task must be created.

**Comment by kytrinyx** [comment]
Thanks @joelwallis I've opened a new issue in the discussions repository, and will go ahead and close this one.
