### ISSUE TITLE
`jasmine .` throwing error

### ISSUE THREAD

**Issue by ronalson** [exercism/xjavascript#349]
I've first mentioned this issue on #341 to @joelwallis 

---

### Problem

The section "Making the Test Suite Pass" on the README.md files says that we should run the test using `jasmine .`, however this command is not working.

### Details

Typing `jasmine .` throw the following error:

```
module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/*****/Desktop/exercism/javascript/hello-world'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/jasmine/lib/jasmine.js:93:5
    at Array.forEach (native)
    at Jasmine.loadSpecs (/usr/local/lib/node_modules/jasmine/lib/jasmine.js:92:18)
    at Jasmine.execute (/usr/local/lib/node_modules/jasmine/lib/jasmine.js:197:8)
    at runJasmine (/usr/local/lib/node_modules/jasmine/lib/command.js:125:11)
    at Command.run (/usr/local/lib/node_modules/jasmine/lib/command.js:55:9)
```

running just `jasmine` by itself returns:

```
Started

No specs found
Finished in 0.004 seconds
```

The only way I managed to make the testing work was specifying the actual spec file. I mean, I needed to run `jasmine hello-world.spec.js`. Which return the test:

```
Started
...

3 specs, 0 failures
Finished in 0.013 seconds 
```

### Environment

exercism CLI version:
> 2.4.0

jasmine version:
> jasmine v2.6.0
> jasmine-core v2.6.1

**Comment by joelwallis** [comment]
Yeah, same result here:

```
hello-world❯ jasmine
Started


No specs found
Finished in 0.002 seconds
```

This is a documentation problem, not really a bug. We decided to use Jasmine as a globally installed CLI tool instead of a local dependency because we would need to make every exercise a self-contained project, forcing users to have many Jasmine installations - which is not ideal.

So, to fix it we must update all documentation for the JavaScript track that still recommends users to use `jasmine` to test, and instruct them to use `jasmine <test-file.spec.js>` instead.

Thanks for reporting, @ronalson! 🍺
